throughput_threshold: 0.8  # 80% of configured throughput
memory_threshold: 0.8      # 80% of memory limit
cpu_threshold: 0.6         # 60% of CPU
latency_threshold_ms: 3    # 3 milliseconds
prometheus_server_url: http://54.165.20.46:9090/
prometheus_query_period: 1h
prometheus_query_interval_seconds: 30
redis_api_query_interval_seconds: 60  # Interval for Redis API queries (default 1 hour)

# Autoscaling configuration
memory_scaling_percentage: 20  # Percentage increase for memory scaling (default 20%)
throughput_scaling_percentage: 20  # Percentage increase for throughput scaling (default 20%)

cloud_api_query_interval_seconds: 3600  # 1 hour default
cloud_api_query_interval_seconds_autoscale: 60  # 1 minute if autoscaling enabled